config/routes.rb
Rails.application.routes.draw do
  resources :products, :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  def password=(text)
    # You must store encrypted password. 
    self.crypted_password = text
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :set_user_time_zone
  
  protected
  
  def set_user_time_zone
    Time.zone = current_user.time_zone if logged_in?
  end
  
  def current_user
    User.find(session[:user_id]) rescue User.new
  end
  
  def logged_in?
    !session[:user_id].blank?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  
  def show
    @product = Product.find(params[:id])
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(allowed_params)
    if @product.save
      flash[:notice] = "Successfully created product."
      redirect_to products_path
    else
      render :action => 'new'
    end
  end
  
  def edit
    @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(allowed_params)
      flash[:notice] = "Successfully updated product."
      redirect_to products_path
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Successfully destroyed product."
    redirect_to products_path
  end
  
  private
  
  def allowed_params
    params.require(:product).permit(:name, :released_at)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    logger.info Time.zone
    logger.info current_user.email
  end

  def create
    @user = User.new(allowed_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thanks for signing up!"
      
      redirect_to :back
    else
      render :new
    end
  end
  
  private
  
  def allowed_params
    params.require(:user).permit(:email, :password, :time_zone)  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tzone</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
	  
    <div id="container">
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <%- end -%>
            
      <%= yield %>
    </div>
	  
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :released_at %><br />
    <%= f.datetime_select :released_at %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/products/index.html.erb
<% for product in @products %>

<div>
  <h2><%= product.name %></h2>
  <p><strong>Released at:</strong> <%= product.released_at.to_s(:long) %></p>
</div>
<% end %>

<p><%= link_to "New Product", new_product_path %></p>

app/views/products/new.html.erb
<%= render :partial => 'form' %>

<p><%= link_to "Back", products_path %></p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1> Registration </h1> 

<%= form_for :user, :url => users_path do |f| %>
  <p>
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :time_zone %><br />
    <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones %>
  </p>
  <p><%= f.submit "Sign up" %></p>
<% end %>